# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên đồ án')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã đồ án')),
                ('description', models.TextField(verbose_name='Mô tả đồ án')),
                ('category', models.CharField(choices=[('WEB', 'Phát triển Web'), ('MOBILE', 'Lập trình Di động'), ('AI_ML', 'Trí tuệ nhân tạo & Machine Learning'), ('IOT', 'Internet of Things'), ('SYSTEM', 'Hệ thống & Mạng'), ('OTHER', 'Khác')], default='WEB', max_length=50, verbose_name='Thể loại')),
                ('technology', models.CharField(max_length=255, verbose_name='Công nghệ sử dụng')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc (Deadline)')),
                ('status', models.CharField(choices=[('PLANNING', 'Lập kế hoạch'), ('IN_PROGRESS', 'Đang thực hiện'), ('REVIEW', 'Đang chờ Review'), ('COMPLETED', 'Hoàn thành'), ('ARCHIVED', 'Lưu trữ')], default='PLANNING', max_length=20, verbose_name='Trạng thái')),
                ('repo_url', models.URLField(blank=True, null=True, verbose_name='URL Repository (GitHub/GitLab)')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='URL Demo (Live Site)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Trưởng nhóm / Người tạo')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL, verbose_name='Mentor / Giảng viên hướng dẫn')),
            ],
            options={
                'verbose_name': 'Đồ án',
                'verbose_name_plural': 'Danh sách Đồ án',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADER', 'Trưởng nhóm'), ('MEMBER', 'Thành viên')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thành viên đồ án',
                'verbose_name_plural': 'Danh sách Thành viên đồ án',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
