# Generated by Django 5.2.17 on 2026-09-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='mentor_status',
            field=models.CharField(choices=[('NONE', 'Chưa chọn Mentor'), ('PENDING', 'Chờ Mentor xác nhận'), ('ACCEPTED', 'Đã nhận hướng dẫn'), ('REJECTED', 'Mentor từ chối')], default='NONE', max_length=20, verbose_name='Trạng thái xác nhận Mentor'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã tham gia')], default='ACCEPTED', max_length=20),
        ),
    ]
