# Generated by Django 5.2.17 on 2026-09-25 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_mentor_status_projectmember_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã tham gia')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'status'], name='projects_pr_user_id_3f6dd8_idx'),
        ),
    ]
