# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Đăng nhập hệ thống'), ('LOGOUT', 'Đăng xuất hệ thống'), ('CREATE_PROJECT', 'Tạo đồ án mới'), ('UPDATE_PROJECT', 'Cập nhật đồ án'), ('DELETE_PROJECT', 'Xóa đồ án'), ('CREATE_TASK', 'Tạo công việc'), ('UPDATE_TASK', 'Cập nhật công việc'), ('DELETE_TASK', 'Xóa công việc'), ('UPLOAD_DOCUMENT', 'Tải lên tài liệu'), ('DELETE_DOCUMENT', 'Xóa tài liệu'), ('SUBMIT_REVIEW', 'Gửi nhận xét Review'), ('LOCK_USER', 'Khóa tài khoản'), ('UNLOCK_USER', 'Mở khóa tài khoản'), ('SYSTEM_CONFIG', 'Cấu hình hệ thống')], max_length=50, verbose_name='Hành động')),
                ('entity_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Đối tượng tác động')),
                ('entity_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Đối tượng')),
                ('description', models.TextField(verbose_name='Chi tiết nhật ký')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Địa chỉ IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
            options={
                'verbose_name': 'Nhật ký hệ thống',
                'verbose_name_plural': 'Lịch sử hoạt động (Audit Logs)',
                'ordering': ['-created_at'],
            },
        ),
    ]
