# Generated by Django 5.2.17 on 2026-10-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Đăng nhập hệ thống'), ('LOGOUT', 'Đăng xuất hệ thống'), ('CREATE_PROJECT', 'Tạo đồ án mới'), ('UPDATE_PROJECT', 'Cập nhật đồ án'), ('DELETE_PROJECT', 'Xóa đồ án'), ('CREATE_TASK', 'Tạo công việc'), ('UPDATE_TASK', 'Cập nhật công việc'), ('DELETE_TASK', 'Xóa công việc'), ('UPLOAD_DOCUMENT', 'Tải lên tài liệu'), ('DELETE_DOCUMENT', 'Xóa tài liệu'), ('SUBMIT_REVIEW', 'Gửi nhận xét Review'), ('CREATE_MILESTONE', 'Tạo mốc Milestone'), ('UPDATE_MILESTONE', 'Cập nhật mốc Milestone'), ('DELETE_MILESTONE', 'Xóa mốc Milestone'), ('LOCK_USER', 'Khóa tài khoản'), ('UNLOCK_USER', 'Mở khóa tài khoản'), ('SYSTEM_CONFIG', 'Cấu hình hệ thống')], max_length=50, verbose_name='Hành động'),
        ),
    ]
