# Generated by Django 5.2.17 on 2026-10-07 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_alter_activitylog_action'),
        ('projects', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='projects.project', verbose_name='Đồ án liên quan'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Đăng nhập hệ thống'), ('LOGOUT', 'Đăng xuất hệ thống'), ('CREATE_PROJECT', 'Tạo đồ án mới'), ('UPDATE_PROJECT', 'Cập nhật đồ án'), ('DELETE_PROJECT', 'Xóa đồ án'), ('CREATE_TASK', 'Tạo công việc'), ('UPDATE_TASK', 'Cập nhật công việc'), ('DELETE_TASK', 'Xóa công việc'), ('UPLOAD_DOCUMENT', 'Tải lên tài liệu'), ('DELETE_DOCUMENT', 'Xóa tài liệu'), ('SUBMIT_REVIEW', 'Gửi nhận xét Review'), ('CREATE_MILESTONE', 'Tạo mốc Milestone'), ('UPDATE_MILESTONE', 'Cập nhật mốc Milestone'), ('DELETE_MILESTONE', 'Xóa mốc Milestone'), ('LOCK_USER', 'Khóa tài khoản'), ('UNLOCK_USER', 'Mở khóa tài khoản'), ('SYSTEM_CONFIG', 'Cấu hình hệ thống'), ('CREATE_USER', 'Tạo người dùng'), ('UPDATE_USER', 'Cập nhật người dùng'), ('CHANGE_ROLE', 'Đổi vai trò người dùng'), ('APPROVE_USER', 'Duyệt giảng viên'), ('REJECT_USER', 'Từ chối đăng ký'), ('RESET_PASSWORD', 'Đặt lại mật khẩu'), ('ADD_COMMENT', 'Thêm bình luận'), ('CHANGE_STATUS', 'Chuyển trạng thái'), ('CREATE_EVENT', 'Tạo sự kiện lịch'), ('UPDATE_EVENT', 'Cập nhật sự kiện lịch'), ('DELETE_EVENT', 'Xóa sự kiện lịch'), ('MEMBER_CHANGE', 'Thay đổi thành viên'), ('AI_GENERATE', 'Yêu cầu AI phân tích'), ('AI_APPLY', 'Áp dụng đề xuất AI'), ('AI_PROPOSE', 'Gửi đề xuất AI')], max_length=50, verbose_name='Hành động'),
        ),
    ]
