# Generated by Django 5.2.17 on 2026-10-06 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_message'),
        ('tasks', '0003_taskchecklistitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời điểm bắt đầu')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm kết thúc')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='Thời lượng (giây)')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú công việc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='projects.project', verbose_name='Đồ án')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='tasks.task', verbose_name='Công việc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Nhật ký thời gian (Time Log)',
                'verbose_name_plural': 'Danh sách Nhật ký thời gian',
                'ordering': ['-started_at'],
            },
        ),
    ]
