# Generated by Django 5.2.17 on 2026-10-06 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('NAVY', 'Navy (Mặc định)'), ('FOREST', 'Forest Green'), ('PLUM', 'Royal Plum'), ('EMBER', 'Warm Ember')], default='NAVY', max_length=20, verbose_name='Giao diện Accent')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Thông báo qua Email')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='Thông báo trong Ứng dụng')),
                ('deadline_reminders', models.BooleanField(default=True, verbose_name='Nhắc nhở Hạn chót')),
                ('week_start', models.CharField(choices=[('MON', 'Thứ 2'), ('SUN', 'Chủ nhật')], default='MON', max_length=10, verbose_name='Ngày bắt đầu tuần')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lúc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Cấu hình Người dùng',
                'verbose_name_plural': 'Danh sách Cấu hình Người dùng',
            },
        ),
    ]
