# Generated by Django 5.2.17 on 2026-10-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Sinh viên'), ('MENTOR', 'Giảng viên / Mentor'), ('ADMIN', 'Quản trị viên HVHK')], default='STUDENT', max_length=20, verbose_name='Vai trò'),
        ),
    ]
