# Generated by Django 5.2.17 on 2026-10-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('SUSPENDED', 'Đã khóa'), ('PENDING_APPROVAL', 'Chờ duyệt')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
