# Generated by Django 5.2.17 on 2026-10-07 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_status'),
        ('projects', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='last_ai_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Đồ án AI xem gần nhất'),
        ),
    ]
