# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tên tài liệu')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='Tệp đính kèm')),
                ('file_type', models.CharField(choices=[('PDF', 'Tài liệu PDF'), ('WORD', 'Word (DOC/DOCX)'), ('EXCEL', 'Excel (XLS/XLSX)'), ('POWERPOINT', 'PowerPoint (PPT/PPTX)'), ('ZIP', 'File Nén (ZIP/RAR)'), ('IMAGE', 'Hình ảnh'), ('CODE', 'Mã nguồn / Text'), ('OTHER', 'Khác')], default='PDF', max_length=20, verbose_name='Loại tệp')),
                ('file_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dung lượng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả tài liệu')),
                ('current_version', models.IntegerField(default=1, verbose_name='Phiên bản hiện tại')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='Đồ án')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Người tải lên')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Danh sách Tài liệu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_documents/versions/', verbose_name='Tệp phiên bản')),
                ('version_number', models.IntegerField(verbose_name='Số phiên bản')),
                ('change_log', models.TextField(blank=True, null=True, verbose_name='Ghi chú thay đổi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Tài liệu')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Phiên bản tài liệu',
                'verbose_name_plural': 'Lịch sử phiên bản tài liệu',
                'ordering': ['-version_number'],
            },
        ),
    ]
