# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung nhận xét & Nhận xét chi tiết')),
                ('rating', models.IntegerField(choices=[(1, '1 Sao'), (2, '2 Sao'), (3, '3 Sao'), (4, '4 Sao'), (5, '5 Sao')], default=5, verbose_name='Đánh giá (1-5 Sao)')),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ Review'), ('APPROVED', 'Đã duyệt (Approved)'), ('NEED_REVISION', 'Cần chỉnh sửa (Need Revision)')], default='APPROVED', max_length=20, verbose_name='Kết quả đánh giá')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Mentor đánh giá')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='milestones.milestone', verbose_name='Milestone liên quan')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='projects.project', verbose_name='Đồ án')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='tasks.task', verbose_name='Công việc liên quan')),
            ],
            options={
                'verbose_name': 'Nhận xét & Review',
                'verbose_name_plural': 'Danh sách Review & Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
