# Generated by Django 5.2.17 on 2026-10-07 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận đã xử lý'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận đã xử lý'),
        ),
    ]
