# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Giai đoạn / Milestone')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả công việc')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('due_date', models.DateField(verbose_name='Hạn hoàn thành')),
                ('status', models.CharField(choices=[('PENDING', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành'), ('OVERDUE', 'Quá hạn')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Milestone',
                'verbose_name_plural': 'Danh sách Milestone',
                'ordering': ['due_date'],
            },
        ),
    ]
