# Generated by Django 5.2.17 on 2026-09-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Chưa bắt đầu'), ('IN_PROGRESS', 'Đang thực hiện'), ('COMPLETED', 'Đã hoàn thành'), ('OVERDUE', 'Quá hạn')], db_index=True, default='PENDING', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
