# Generated by Django 5.2.17 on 2026-10-06 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0002_alter_milestone_status'),
        ('projects', '0004_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề sự kiện')),
                ('event_type', models.CharField(choices=[('MEETING', 'Họp nhóm / Mentor'), ('REVIEW', 'Đánh giá / Nộp bản thảo'), ('DEADLINE', 'Hạn chót công việc'), ('PERSONAL', 'Cá nhân / Lịch hẹn')], default='MEETING', max_length=20, verbose_name='Loại sự kiện')),
                ('start', models.DateTimeField(verbose_name='Bắt đầu')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Kết thúc')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Link Họp trực tuyến')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã xác nhận'), ('REJECTED', 'Đã từ chối')], default='ACCEPTED', max_length=20, verbose_name='Trạng thái xác nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('participants', models.ManyToManyField(blank=True, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='Thành viên tham gia')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Sự kiện lịch',
                'verbose_name_plural': 'Danh sách Sự kiện lịch',
                'ordering': ['start'],
            },
        ),
    ]
