# Generated by Django 5.2.17 on 2026-10-07 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0003_event'),
        ('projects', '0004_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề cuộc hẹn')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú / Nội dung')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ xác nhận'), ('ACCEPTED', 'Đã đồng ý'), ('DECLINED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm / Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Mentor / Giảng viên')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='projects.project', verbose_name='Đồ án')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Sinh viên')),
            ],
            options={
                'verbose_name': 'Lịch hẹn Mentor',
                'verbose_name_plural': 'Danh sách Lịch hẹn Mentor',
                'ordering': ['start_time'],
            },
        ),
    ]
