# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('TASK_BREAKDOWN', 'Phân rã Task (AI Task Breakdown)'), ('WEEKLY_SUMMARY', 'Báo cáo tuần (AI Weekly Summary)'), ('RISK_DETECTION', 'Cảnh báo rủi ro (AI Risk Detection)'), ('MENTOR_QUESTIONS', 'Gợi ý câu hỏi Mentor (AI Questions)')], max_length=30, verbose_name='Loại tác vụ AI')),
                ('input_data', models.TextField(verbose_name='Dữ liệu đầu vào')),
                ('output_result', models.TextField(verbose_name='Kết quả AI tạo ra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to='projects.project', verbose_name='Đồ án liên quan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người yêu cầu')),
            ],
            options={
                'verbose_name': 'Yêu cầu AI',
                'verbose_name_plural': 'Lịch sử Yêu cầu AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
