# Generated by Django 5.2.17 on 2026-09-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('projects', '0003_alter_projectmember_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField(verbose_name='Tuần thứ')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('summary_text', models.TextField(verbose_name='Nội dung tóm tắt tiến độ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_summaries', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Tóm tắt tiến độ tuần',
                'verbose_name_plural': 'Danh sách Tóm tắt tiến độ tuần',
                'ordering': ['-year', '-week_number', '-created_at'],
                'unique_together': {('project', 'week_number', 'year')},
            },
        ),
    ]
