# Generated by Django 5.2.17 on 2026-10-07 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_weeklysummary'),
        ('projects', '0004_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='cached',
            field=models.BooleanField(default=False, verbose_name='Lấy từ Cache'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='context_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Hash ngữ cảnh'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Thông tin lỗi'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='latency_ms',
            field=models.IntegerField(default=0, verbose_name='Độ trễ (ms)'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='model',
            field=models.CharField(default='none', max_length=100, verbose_name='Mô hình LLM'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='provider',
            field=models.CharField(default='none', max_length=50, verbose_name='Nhà cung cấp'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='source',
            field=models.CharField(default='rules', max_length=20, verbose_name='Nguồn tạo kết quả (llm/rules)'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Thành công (LLM)'), ('FALLBACK', 'Dự phòng (Rules)'), ('ERROR', 'Thất bại')], default='SUCCESS', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='tokens_in',
            field=models.IntegerField(default=0, verbose_name='Tokens đầu vào'),
        ),
        migrations.AddField(
            model_name='airequest',
            name='tokens_out',
            field=models.IntegerField(default=0, verbose_name='Tokens đầu ra'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Model LLM'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='rating',
            field=models.CharField(default='FAIR', max_length=20, verbose_name='Đánh giá chung (GOOD/FAIR/AT_RISK)'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='source',
            field=models.CharField(default='rules', max_length=20, verbose_name='Nguồn (llm/rules)'),
        ),
        migrations.AlterField(
            model_name='airequest',
            name='prompt_type',
            field=models.CharField(choices=[('TASK_BREAKDOWN', 'Phân rã Task (AI Task Breakdown)'), ('WEEKLY_SUMMARY', 'Báo cáo tuần (AI Weekly Summary)'), ('RISK_DETECTION', 'Cảnh báo rủi ro (AI Risk Detection)'), ('MENTOR_QUESTIONS', 'Gợi ý câu hỏi Mentor (AI Questions)'), ('CHAT', 'Trò chuyện AI (AI Chat)')], max_length=30, verbose_name='Loại tác vụ AI'),
        ),
        migrations.CreateModel(
            name='AIProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='task_breakdown', max_length=50, verbose_name='Loại đề xuất')),
                ('payload', models.JSONField(default=dict, verbose_name='Dữ liệu JSON đề xuất')),
                ('status', models.CharField(choices=[('PENDING', 'Chờ duyệt'), ('APPLIED', 'Đã áp dụng'), ('REJECTED', 'Từ chối'), ('CANCELLED', 'Đã hủy')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xử lý')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú xử lý')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='projects.project', verbose_name='Đồ án')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Người đề xuất')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_ai_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý')),
            ],
            options={
                'verbose_name': 'Đề xuất AI',
                'verbose_name_plural': 'Danh sách Đề xuất AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
