# Generated by Django 5.2.17 on 2026-10-07 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_airequest_cached_airequest_context_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysummary',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_weekly_summaries', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='iso_week',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tuần ISO'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='iso_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Năm ISO'),
        ),
    ]
