# Generated by Django 5.2.17 on 2026-10-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_weeklysummary_generated_by_weeklysummary_iso_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='structured_output',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dữ liệu cấu trúc'),
        ),
        migrations.AddField(
            model_name='weeklysummary',
            name='structured',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Dữ liệu JSON cấu trúc'),
        ),
    ]
