# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề công việc')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Chi tiết công việc')),
                ('priority', models.CharField(choices=[('LOW', 'Thấp'), ('MEDIUM', 'Trung bình'), ('HIGH', 'Cao'), ('CRITICAL', 'Khẩn cấp')], default='MEDIUM', max_length=20, verbose_name='Độ ưu tiên')),
                ('status', models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang làm'), ('REVIEW', 'Đang Review'), ('DONE', 'Hoàn thành')], default='TODO', max_length=20, verbose_name='Trạng thái')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Hạn hoàn thành')),
                ('labels', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nhãn (cách nhau bởi dấu phẩy)')),
                ('order_index', models.IntegerField(default=0, verbose_name='Thứ tự Kanban')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='milestones.milestone', verbose_name='Milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Công việc',
                'verbose_name_plural': 'Danh sách Công việc',
                'ordering': ['order_index', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Công việc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận công việc',
                'ordering': ['created_at'],
            },
        ),
    ]
