# Generated by Django 5.2.17 on 2026-09-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectmember_status_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Hạn hoàn thành'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang làm'), ('REVIEW', 'Đang Review'), ('DONE', 'Hoàn thành')], db_index=True, default='TODO', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bảng Kanban Đồ án', max_length=255, verbose_name='Tên Bảng')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Bảng Kanban',
                'verbose_name_plural': 'Danh sách Bảng Kanban',
            },
        ),
        migrations.CreateModel(
            name='BoardColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tên cột')),
                ('status_code', models.CharField(choices=[('TODO', 'Cần làm'), ('IN_PROGRESS', 'Đang làm'), ('REVIEW', 'Đang Review'), ('DONE', 'Hoàn thành')], default='TODO', max_length=50, verbose_name='Mã trạng thái tương ứng')),
                ('order_index', models.IntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='tasks.board', verbose_name='Bảng Kanban')),
            ],
            options={
                'verbose_name': 'Cột Bảng Kanban',
                'verbose_name_plural': 'Danh sách Cột Bảng Kanban',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='board_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.boardcolumn', verbose_name='Cột Kanban'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Sprint')),
                ('goal', models.TextField(blank=True, null=True, verbose_name='Mục tiêu Sprint')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sprint đang chạy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='projects.project', verbose_name='Đồ án')),
            ],
            options={
                'verbose_name': 'Sprint',
                'verbose_name_plural': 'Danh sách Sprint',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.sprint', verbose_name='Sprint (Scrum)'),
        ),
    ]
