# Generated by Django 5.2.17 on 2026-10-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date_alter_task_status_board_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nội dung mục cần làm')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Đã hoàn thành')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='tasks.task', verbose_name='Công việc')),
            ],
            options={
                'verbose_name': 'Checklist công việc',
                'verbose_name_plural': 'Danh sách Checklist công việc',
                'ordering': ['created_at'],
            },
        ),
    ]
