# Generated by Django 5.2.17 on 2026-10-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskchecklistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm hoàn thành'),
        ),
        migrations.AddField(
            model_name='task',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm đổi trạng thái gần nhất'),
        ),
    ]
