# Generated by Django 5.2.17 on 2026-10-07 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completed_at_task_status_changed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcolumn',
            name='board',
        ),
        migrations.RemoveField(
            model_name='task',
            name='board_column',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardColumn',
        ),
    ]
