# Generated by Django 5.2.17 on 2026-09-25 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề thông báo')),
                ('message', models.TextField(verbose_name='Nội dung thông báo')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Đường dẫn chuyển hướng')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Được phân công Task'), ('TASK_OVERDUE', 'Task quá hạn'), ('MENTOR_FEEDBACK', 'Phản hồi từ Mentor'), ('PROJECT_INVITE', 'Lời mời vào Đồ án'), ('COMMENT', 'Bình luận mới'), ('MILESTONE_DUE', 'Milestone sắp đến hạn'), ('PROJECT_APPROVED', 'Đồ án được thông qua'), ('SYSTEM', 'Thông báo hệ thống')], default='SYSTEM', max_length=30, verbose_name='Loại thông báo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người nhận')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Người gửi')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Danh sách Thông báo',
                'ordering': ['-created_at'],
            },
        ),
    ]
