# Generated by Django 5.2.17 on 2026-10-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Được phân công Task'), ('TASK_OVERDUE', 'Task quá hạn'), ('MENTOR_FEEDBACK', 'Phản hồi từ Mentor'), ('PROJECT_INVITE', 'Lời mời vào Đồ án'), ('PROJECT_ACCEPTED', 'Đồ án được nhận hướng dẫn'), ('PROJECT_REJECTED', 'Đồ án bị từ chối hướng dẫn'), ('RISK_WARNING', 'Cảnh báo rủi ro tiến độ'), ('COMMENT', 'Bình luận mới'), ('MILESTONE_DUE', 'Milestone sắp đến hạn'), ('PROJECT_APPROVED', 'Đồ án được thông qua'), ('SUBMIT_REVIEW', 'Nộp đồ án chờ nghiệm thu'), ('WEEKLY_SUMMARY', 'Báo cáo tóm tắt tuần'), ('SYSTEM', 'Thông báo hệ thống')], default='SYSTEM', max_length=30, verbose_name='Loại thông báo'),
        ),
    ]
